version: '3.1'

services:
  mariadb:
    image: mariadb:10.0.29
    environment:
      MYSQL_ROOT_PASSWORD: rootUserPassword
      MYSQL_USER: dataUser
      MYSQL_PASSWORD: dataUserPassword
    volumes:
      - ./mysql-config:/etc/mysql/conf.d
      - ./schemas:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

    # Uncomment this to disable double write buffer, improve loading speed
    # command: ["--innodb-doublewrite=0"]
