version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysqlRootPassword
      MYSQL_USER: dataUser
      MYSQL_PASSWORD: dataUserPassword
    volumes:
      - ./mysql-config:/etc/mysql/conf.d
      - ./schemas:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
